module.exports = [
  "Adult",
  "Art, Books and Photo",
  "Career",
  "Computer Software",
  "Communities > Dating",
  "Communities > Online Surveys",
  "Communities > Psychic and Astrology",
  "Communities > Social Networks",
  "Downloads and Toolbars",
  "Education > Children",
  "Education > Languages",
  "Education > Skills",
  "Education > Professional",
  "Entertainment > Music, TV and Videos",
  "Entertainment > Events and Outdoors",
  "Entertainment > Mobile Entertainment",
  "Food & Drinks",
  "Finances > Loan Services",
  "Finances > Banking",
  "Finances > Tax Services",
  "Finances > Investment ",
  "Finances > Advise and Others",
  "Games > Browser Games",
  "Games > Client Games",
  "Games > Betting and Gambling",
  "Health, Sports and Wellness",
  "Insurance",
  "Lead Generation",
  "Legal Services",
  "Marketing > Business-to-Business",
  "Marketing > Domain Registration",
  "Marketing > Web Design",
  "Marketing > Web Hosting/Servers",
  "Marketing > E-commerce Solutions",
  "Non-Profit > ",
  "Real Estate Services",
  "Services",
  "Shopping > Auction and Classifieds",
  "Shopping > Coupons and Discounts",
  "Shopping > Virtual Malls",
  "Shopping > Automotive",
  "Shopping > Groceries",
  "Shopping > Beauty and Fragrance",
  "Shopping > Clothing and Apparel",
  "Shopping > Gifts and Flowers",
  "Shopping > Electronics",
  "Shopping > Home and Garden",
  "Shopping > Miscellaneous",
  "Shopping > Sports and Travel",
  "Shopping > B2B",
  "Telecommunications > Wireless",
  "Telecommunications > Mobile",
  "Telecommunications > Phone Services",
  "Travel > Car Rentals",
  "Travel > Flights and Hotels",
  "Travel > Services and Supplies",
  "Digital Products > Arts & Entertainment ",
  "Digital Products > Betting Systems",
  "Digital Products > Business/Investing",
  "Digital Products > Computers/Internet ",
  "Digital Products > Cooking, Food & Wine ",
  "Digital Products > E-Business & E-Marketing",
  "Digital Products > Education ",
  "Digital Products > Employment & Jobs",
  "Digital Products > Fiction",
  "Digital Products > Games",
  "Digital Products > Green Products",
  "Digital Products > Health & Fitness",
  "Digital Products > Home & Garden ",
  "Digital Products > Languages ",
  "Digital Products > Mobile",
  "Digital Products > Parenting & Families",
  "Digital Products > Politics/Current Events",
  "Digital Products > Self-Help",
  "Digital Products > Software & Services",
  "Digital Products > Spirituality & Alternative ",
  "Digital Products > Sports",
  "Digital Products > Travel",
  "Digital Products > Reference and others",
]
